scripts/card/card.gd

feat: Refactoring Initialize Function

---

scenes/encounters/battle.tscn
scripts/battle/card_handler.gd
scripts/battle/card_ui.gd
scripts/battle/card_ui.gd.uid

I had the freedom to add a "Grave"- Button for the Grave Mechanic (,without a signal), so I can better estimate how big the space will be. I will undo it, should this pose a problem.

Feature/42 battel UI

---

project.godot

configures scaling mode to automatically scale to viewport size 
closes #51

chore: Viewport settings

---

scripts/card/card.gd
scripts/enemy/enemy.gd

refactor: fixed targeting functions

---

resources/characters/test_character_cards.tres
scenes/card/card.tscn
scripts/battle/card_handler.gd
scripts/card/card.gd

wrote functions to add cards to hand and to draw cards from draw pile closes #43

feat: card drawing

---

resources/enemies/normal_attack.tres
resources/enemies/swift_attack.tres
resources/enemies/test_enemy.tres
scenes/encounters/battle.tscn
scenes/enemy/enemy.tscn
scripts/battle/enemy_handler.gd
scripts/battle/enemy_handler.gd.uid
scripts/enemy/enemy.gd

I also added a littel entering animation for the enemy closes #65

feat: creating and loading a test enemy

---

scripts/enemy/enemy.gd

feat: Enemies choosing Intent

---

scripts/battle/enemy_handler.gd

feat:EnemyHandling

---

project.godot
scenes/card/card.tscn
scenes/encounters/battle.tscn
scenes/enemy/enemy.tscn
scripts/battle/card_handler.gd
scripts/battle/enemy_handler.gd

changed resolution to 320x180
closes #80

refactor: resizing game

---

project.godot
scripts/global/event_bus_handler.gd
scripts/global/event_bus_handler.gd.uid

Added the first events that will trigger effects during combat. Further events can be added in the future 
closes #81

feat: event bus autoload script

---

scenes/encounters/battle.tscn
scenes/map/map.tscn
scenes/ui/battle_ui.tscn
scenes/ui/run.tscn
scripts/battle/battle_ui.gd
scripts/battle/state_machine/card_highlighted.gd
scripts/battle/state_machine/exit.gd
scripts/battle/state_machine/idle.gd
scripts/battle/state_machine/player_start_turn.gd
scripts/battle/state_machine/state.gd
scripts/battle/state_machine/state_machine.gd
scripts/global/event_bus_handler.gd
scripts/map/map.gd
scripts/ui/run.gd
scripts/ui/ui_layer.gd
scripts/ui/ui_layer.gd.uid

Added extra events for the communication that now can't happen directly. I also moved the character to a better position. closes #87

refactor: moved all UI elements to one canvas layer

---

scenes/encounters/battle.tscn
scripts/battle/battle.gd
scripts/battle/battle.gd.uid
scripts/battle/card_handler.gd
scripts/battle/enemy_handler.gd
scripts/battle/state_machine/state_machine.gd
scripts/global/event_bus_handler.gd
scripts/run/encounter_handler.gd
scripts/ui/ui_layer.gd

Added a script to the battle scene that initializes its components in the right order rather than using _ready() functions. Also minor clean code and bug fixes.
closes #90

feat: Initialize battle sequence

---

scenes/main.tscn
scenes/ui/close_game_confirmation.tscn
scenes/ui/main_menu.tscn
scenes/ui/pause_menu_layer.tscn
scripts/main.gd
scripts/ui/close_game_confirmation.gd
scripts/ui/close_game_confirmation.gd.uid
scripts/ui/main_menu.gd
scripts/ui/main_menu.gd.uid
scripts/ui/pause_menu_layer.gd

added main menu and changed pause menu/options to now load different buttons depending on where they are opened from closes #116

feat: main menu

---

scenes/card/card_visualization.tscn
scenes/encounters/battle_reward_button.tscn
scenes/encounters/battle_rewards.tscn
scenes/ui/select_card_screen.tscn
scripts/card/card_visualization.gd
scripts/card/card_visualization.gd.uid
scripts/rewards/battle_reward_button.gd
scripts/rewards/battle_reward_button.gd.uid
scripts/rewards/battle_rewards.gd
scripts/rewards/battle_rewards.gd.uid
scripts/ui/select_card_screen.gd
scripts/ui/select_card_screen.gd.uid

added battle reward, card selection screen and and card visualization scene for scenes that need the card visuals but not the play logic closes #126

feat: battle rewards

---

scenes/encounters/battle.tscn
scripts/battle/battle.gd
scripts/battle/battle_ui.gd
scripts/battle/card_handler.gd
scripts/battle/state_machine/exit.gd
scripts/battle/state_machine/idle.gd
scripts/battle/state_machine/player_end_turn.gd
scripts/battle/state_machine/state_machine.gd
scripts/card/card.gd
scripts/characters/player.gd
scripts/global/event_bus_handler.gd
scripts/main.gd
scripts/ui/run_ui.gd
scripts/ui/ui_layer.gd

feat: event handler cleanup

---

resources/cards/prepare.tres
resources/cards/wound.tres
resources/characters/card_library.tres
scripts/custom_resources/effect_action.gd
scripts/effects/effect_handler.gd
scripts/effects/effect_instances/gather.gd

implemented effect action, added cards for testing and fixed gather effect logic 
closes #135

feat: effect action

---

resources/cards/defend.tres
resources/cards/prepare.tres
resources/cards/strike.tres
resources/cards/wound.tres
resources/tooltips/agile_tooltip.tres
resources/tooltips/attack_tooltip.tres
resources/tooltips/block_tooltip.tres
resources/tooltips/damokles_sword_tooltip.tres
resources/tooltips/gather_tooltip.tres
resources/tooltips/incapacitated_tooltip.tres
resources/tooltips/phalanx_tooltip.tres
resources/tooltips/regeneration_tooltip.tres
resources/tooltips/vigilant_tooltip.tres
resources/tooltips/warriors_furry_tooltip.tres
resources/tooltips/wounded_tooltip.tres
scenes/ui/run.tscn
scenes/ui/run_ui.tscn
scenes/ui/tooltip.tscn
scripts/battle/card_handler.gd
scripts/custom_resources/card_type.gd
scripts/custom_resources/tooltip_data.gd
scripts/custom_resources/tooltip_data.gd.uid
scripts/global/event_bus_handler.gd
scripts/ui/run_ui.gd
scripts/ui/tooltip.gd
scripts/ui/tooltip.gd.uid

feat: tooltips

---

resources/cards/warrior/common/guard.tres
resources/cards/warrior/common/hit.tres
scripts/custom_resources/card_manipulation_action.gd

fix: fixed discard action

---

scripts/battle/card_handler.gd

fix: fixed card drawing bug

---

scripts/custom_resources/special_action.gd

thanatos now properly checks the effects in the players effect handler
closes #173

fix: fixed crash when playing thanatos

---

scripts/battle/card_handler.gd
scripts/battle/state_machine/exit.gd
scripts/effects/effect_instances/agile.gd
scripts/effects/effect_instances/incapacitated.gd
scripts/encounters/campfire.gd
scripts/global/artifact_handler.gd
scripts/global/run_data.gd

introduced altered values that now get cleared after every battle
closes #190

fix: fixed parma agile bug

---

scripts/battle/card_handler.gd

fix: called the correct function to deselect the card when the player looses control

---

project.godot

fix: removed reference to deleted cursor

---

scripts/global/deck_handler.gd
scripts/rewards/battle_reward_button.gd
scripts/rewards/battle_rewards.gd

removed coins and updated boss rewards to load only god cards
closes #230

feat: updated card rewards for medianight release version

---

resources/shaders/hit_frame_shader.gdshader
scripts/enemy/enemy.gd

fix: dulicating shader material for enemies

---

resources/encounters/battle_stage_0.tres
resources/encounters/battle_stage_1_1.tres
resources/encounters/battle_stage_1_2.tres
resources/encounters/battle_stage_1_3.tres
resources/encounters/battle_stage_2_1.tres
resources/encounters/battle_stage_2_2.tres
resources/encounters/battle_stage_2_3.tres
resources/encounters/boss_battle_medusa.tres
resources/encounters/mini_boss_battle_minotaur.tres
resources/enemies/chimera.tres
resources/enemies/gorgone.tres
resources/enemies/medusa.tres
resources/enemies/minotaur.tres
resources/enemies/orthos.tres
resources/enemies/siren.tres
scripts/battle/battle.gd
scripts/custom_resources/map/battle_encounter.gd
scripts/custom_resources/map/boss_encounter.gd
scripts/custom_resources/map/mini_boss_encounter.gd
scripts/map/map.gd
scripts/run/encounter_handler.gd
scripts/run/run.gd
scripts/ui/ui_layer.gd

the encounter handler now loads a variety of different battles, depending on the layer in the map.
closes #219

feat: encounter loading

---

scripts/battle/enemy_handler.gd

refactor: changed calculation for enemy position

---

resources/encounters/battle_stage_1_1.tres
resources/encounters/battle_stage_1_2.tres
resources/encounters/battle_stage_1_3.tres
resources/encounters/battle_stage_2_1.tres
resources/encounters/battle_stage_2_2.tres
resources/encounters/battle_stage_2_3.tres

unused field difficulty in battle resource
closes #258

refactor: remove battle difficulty

---

resources/characters/Warrior_Stats.tres
resources/enemies/chimera.tres
resources/enemies/gorgone.tres
resources/enemies/medusa.tres
resources/enemies/minotaur.tres
resources/enemies/orthos.tres
resources/enemies/siren.tres
scripts/custom_resources/entity_stats.gd
scripts/custom_resources/player_stats.gd
scripts/run/run.gd

fix: stats now reset after run

---

resources/cards/warrior/common/parry.tres

fixed parry card and removed sub resource
closes #255

feat: fix parry card

---

scripts/battle/enemy_handler.gd

setting enemy id to -1 if the enemy dies
closes #241

fix: card playing without target fix

---

scenes/ui/win_screen.tscn
scripts/battle/battle.gd
scripts/run/encounter_handler.gd
scripts/ui/game_over_screen.gd
scripts/ui/win_screen.gd
scripts/ui/win_screen.gd.uid

closes: 231 win the game

---

scenes/ui/battle_ui.tscn
scripts/battle/battle_ui.gd
scripts/battle/card_handler.gd
scripts/global/event_bus_handler.gd

handled conntection via event bus
closes #274

feat: added card pile card count labels

---

scenes/encounters/battle.tscn
scripts/battle/battle.gd
scripts/battle/card_handler.gd
scripts/battle/state_machine/idle.gd

feat: check for it being the players turn when giving control back

---

resources/enemies/minotaur.tres

added AttackActions to Minotaurs second attack so the game wont break lol
closes #285

fix: minotaur second attack

---

scripts/run/encounter_handler.gd

fix: 292 win screen

---

scripts/battle/enemy_handler.gd
scripts/enemy/enemy.gd

added timer between enemy action and slightly decreaced time between different enemies acting
closes #310

feat: enemy action timings

---

scripts/run/encounter_handler.gd

also prepared shop implementation into random encounter
closes #309

refactor: remove campfire from random encounter

---

scenes/encounters/battle_rewards.tscn
scenes/run.tscn
scripts/encounters/campfire.gd
scripts/encounters/dialogue.gd
scripts/encounters/shop.gd
scripts/global/event_bus_handler.gd
scripts/rewards/battle_rewards.gd
scripts/run/encounter_handler.gd
scripts/run/run.gd
scripts/ui/ui_layer.gd

now only one signal is used for finishing any encounter instead of one for each kind of encounter.
closes #304

refactor: standardized encounter finishing

---

resources/enemies/chimera.tres
resources/enemies/gorgone.tres
resources/enemies/medusa.tres
resources/enemies/minotaur.tres
resources/enemies/orthos.tres
resources/enemies/siren.tres
resources/enemies/test_enemy.tres
resources/tooltips/enemy_tooltips/enemy_attack_tooltip.tres
resources/tooltips/enemy_tooltips/enemy_buff_tooltip.tres
resources/tooltips/enemy_tooltips/enemy_debuff_tooltip.tres
resources/tooltips/enemy_tooltips/enemy_defend_tooltip.tres
resources/tooltips/enemy_tooltips/enemy_questionmark_action_tooltip.tres
scenes/enemy/enemy.tscn
scenes/ui/enemy_hud.tscn
scripts/custom_resources/enemy_action.gd
scripts/custom_resources/enemy_stats.gd
scripts/enemy/enemy.gd
scripts/ui/enemy_hud.gd

feat: added enemy intent tooltips

---

resources/cards/warrior/common/prepare.tres
resources/cards/warrior/common/respite.tres
resources/cards/warrior/common/scrape.tres
resources/cards/warrior/gods_boon/ker.tres
resources/cards/warrior/gods_boon/poseidon.tres
resources/cards/warrior/gods_boon/zeus.tres
resources/cards/warrior/hero/actaeon.tres
resources/cards/warrior/hero/damokles.tres
resources/cards/warrior/hero/nestor.tres
resources/cards/warrior/hero/odysseus.tres
resources/characters/warrior_cards.tres

feat: added new cards to card rewards, set a value for zeus

---

scripts/battle/battle.gd
scripts/battle/enemy_handler.gd
scripts/enemy/enemy.gd

moved the responsibility of handling the acting of enemies to the enemy handler
closes #388

fix: skipping the turns of dead enemies

---

scripts/shop/shop_trading_interface.gd

fix: clearing selected cards array when closing
